export const RESTAURANT_BEGIN = 'RESTAURANT_BEGIN';
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const FETCH_RESTAURANT = 'FETCH_RESTAURANT';
export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const EDIT_RESTAURANT = 'EDIT_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
